version: "3"


services:
  ca:
    build:
      context: .
      dockerfile: ./docker/omgwtfssl/Dockerfile
    environment:
      - SSL_SUBJECT="hogehoge.com"
      - SSL_DNS="hogehoge.com"
    volumes:
      - ./nginx-conf.d/ssl:/certs

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 443:443
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
    tty: true
    depends_on:
      ca:
        condition: service_completed_successfully
